spring.application.name=springPracticalDemo

spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=Kshitij@123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=n/BcSh5t7+V+4pl5WvCSuhIAJmVMFff/9m0g9fLGPS0=
jwt.issuer=coderarmy-api
jwt.expiry=900