#Common
spring.application.name = Lecture18-ProfileAndYAMLDemo
app.welcome.code = 200
app.welcome.users = Kshitij, Rajendra, Varshikar


app.welcome.message = LOCAL: Hello, welcome  to my application

#Always Listen Two Properties common and specific (i.e. dev, prod, stag)
#spring.profiles.active=dev
#spring.profiles.active=staging
#spring.profiles.active=prod
